apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"prometheus","app.kubernetes.io/name":"prometheus-1","k8s-app":"prometheus"},"name":"prometheus-1-prometheus","namespace":"grafana","ownerReferences":[{"apiVersion":"app.k8s.io/v1beta1","blockOwnerDeletion":true,"kind":"Application","name":"prometheus-1","uid":"e5538ccd-e2bf-42ff-9ba5-d8a2d01aad3c"}]},"spec":{"ports":[{"name":"http","port":9090,"protocol":"TCP","targetPort":9090}],"selector":{"k8s-app":"prometheus"},"sessionAffinity":"ClientIP"}}
  creationTimestamp: "2022-06-09T14:47:28Z"
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: prometheus-1
    k8s-app: prometheus
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/name: {}
          f:k8s-app: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"e5538ccd-e2bf-42ff-9ba5-d8a2d01aad3c"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":9090,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:k8s-app: {}
        f:sessionAffinity: {}
        f:sessionAffinityConfig:
          .: {}
          f:clientIP:
            .: {}
            f:timeoutSeconds: {}
        f:type: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2022-06-09T14:47:28Z"
  name: prometheus-1-prometheus
  namespace: grafana
  ownerReferences:
  - apiVersion: app.k8s.io/v1beta1
    blockOwnerDeletion: true
    kind: Application
    name: prometheus-1
    uid: e5538ccd-e2bf-42ff-9ba5-d8a2d01aad3c
  resourceVersion: "5711"
  uid: 00f2efcf-0b7e-41c3-9199-47bb6b943f09
spec:
  clusterIP: 10.124.2.218
  clusterIPs:
  - 10.124.2.218
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    k8s-app: prometheus
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
status:
  loadBalancer: {}
