apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/name: prometheus-1
    k8s-app: alertmanager
  name: prometheus-1-alertmanager
  namespace: grafana
---
apiVersion: app.k8s.io/v1beta1
blockOwnerDeletion: true
kind: Application
name: prometheus-1
spec:
  ports:
  - name: http
    port: 9093
    protocol: TCP
    targetPort: 9093
    selector: 
      k8s-app: alertmanager
  type: ClusterIP