apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kube-state-metrics
    app.kubernetes.io/name: prometheus-1
    k8s-app: kube-state-metrics
  name: prometheus-1-kube-state-metrics
  namespace: grafana
---
apiVersion: app.k8s.io/v1beta1
blockOwnerDeletion: true
kind: Application
name: prometheus-1
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 8080
    protocol: TCP
    targetPort: http-metrics
  - name: telemetry
    port: 8081
    protocol: TCP
    targetPort: telemetry
    selector: 
      k8s-app: kube-state-metrics