apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: prometheus-1
    k8s-app: grafana
  name: prometheus-1-grafana
  namespace: default
---
apiVersion: app.k8s.io/v1beta1
blockOwnerDeletion: true
kind: Application
name: prometheus-1
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
    selector: 
      k8s-app: grafana
