apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: prometheus-1
    k8s-app: prometheus
  name: prometheus-1-prometheus
  namespace: grafana
---
apiVersion: app.k8s.io/v1beta1
blockOwnerDeletion: true
kind: Application
name: prometheus-1
spec:
  clusterIP: None
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
    selector: 
      k8s-app: prometheus
  sessionAffinity: ClientIP


