# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\"!\n\x0fUsernameRequest\x12\x0e\n\x06userid\x18\x01 \x01(\x05\"(\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0e\n\x06userid\x18\x02 \x01(\t21\n\x05Users\x12(\n\rGetUserByName\x12\x10.UsernameRequest\x1a\x05.Userb\x06proto3')



_USERNAMEREQUEST = DESCRIPTOR.message_types_by_name['UsernameRequest']
_USER = DESCRIPTOR.message_types_by_name['User']
UsernameRequest = _reflection.GeneratedProtocolMessageType('UsernameRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERNAMEREQUEST,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:UsernameRequest)
  })
_sym_db.RegisterMessage(UsernameRequest)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:User)
  })
_sym_db.RegisterMessage(User)

_USERS = DESCRIPTOR.services_by_name['Users']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERNAMEREQUEST._serialized_start=15
  _USERNAMEREQUEST._serialized_end=48
  _USER._serialized_start=50
  _USER._serialized_end=90
  _USERS._serialized_start=92
  _USERS._serialized_end=141
# @@protoc_insertion_point(module_scope)
