# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
import util


class UserAuthItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, username: str=None, password: str=None):  # noqa: E501
        """UserAuthItem - a model defined in Swagger

        :param username: The username of this UserAuthItem.  # noqa: E501
        :type username: str
        :param password: The password of this UserAuthItem.  # noqa: E501
        :type password: str
        """
        self.swagger_types = {
            'username': str,
            'password': str
        }

        self.attribute_map = {
            'username': 'username',
            'password': 'password'
        }

        self._username = username
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'UserAuthItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserAuthItem of this UserAuthItem.  # noqa: E501
        :rtype: UserAuthItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this UserAuthItem.


        :return: The username of this UserAuthItem.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this UserAuthItem.


        :param username: The username of this UserAuthItem.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def password(self) -> str:
        """Gets the password of this UserAuthItem.


        :return: The password of this UserAuthItem.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this UserAuthItem.


        :param password: The password of this UserAuthItem.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password
