# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reviews.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rreviews.proto\"&\n\x11ReviewByIdRequest\x12\x11\n\treview_id\x18\x01 \x01(\t\";\n\x14ReviewsByGameRequest\x12\x0e\n\x06\x61pp_id\x18\x01 \x01(\t\x12\x13\n\x0bmax_results\x18\x02 \x01(\x05\"\xcc\x01\n\nReviewData\x12\x0e\n\x06\x61pp_id\x18\x01 \x01(\t\x12\x11\n\treview_id\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x0e\n\x06review\x18\x04 \x01(\t\x12\x19\n\x11timestamp_created\x18\x05 \x01(\t\x12\x19\n\x11timestamp_updated\x18\x06 \x01(\t\x12\x13\n\x0brecommended\x18\x07 \x01(\t\x12\x15\n\rvotes_helpful\x18\x08 \x01(\t\x12\x17\n\x0f\x61uthor_steam_id\x18\t \x01(\t\"2\n\x12ReviewDataResponse\x12\x1c\n\x07reviews\x18\x01 \x03(\x0b\x32\x0b.ReviewData2u\n\x07Reviews\x12,\n\tGetReview\x12\x12.ReviewByIdRequest\x1a\x0b.ReviewData\x12<\n\x0eGetGameReviews\x12\x15.ReviewsByGameRequest\x1a\x13.ReviewDataResponseb\x06proto3')



_REVIEWBYIDREQUEST = DESCRIPTOR.message_types_by_name['ReviewByIdRequest']
_REVIEWSBYGAMEREQUEST = DESCRIPTOR.message_types_by_name['ReviewsByGameRequest']
_REVIEWDATA = DESCRIPTOR.message_types_by_name['ReviewData']
_REVIEWDATARESPONSE = DESCRIPTOR.message_types_by_name['ReviewDataResponse']
ReviewByIdRequest = _reflection.GeneratedProtocolMessageType('ReviewByIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _REVIEWBYIDREQUEST,
  '__module__' : 'reviews_pb2'
  # @@protoc_insertion_point(class_scope:ReviewByIdRequest)
  })
_sym_db.RegisterMessage(ReviewByIdRequest)

ReviewsByGameRequest = _reflection.GeneratedProtocolMessageType('ReviewsByGameRequest', (_message.Message,), {
  'DESCRIPTOR' : _REVIEWSBYGAMEREQUEST,
  '__module__' : 'reviews_pb2'
  # @@protoc_insertion_point(class_scope:ReviewsByGameRequest)
  })
_sym_db.RegisterMessage(ReviewsByGameRequest)

ReviewData = _reflection.GeneratedProtocolMessageType('ReviewData', (_message.Message,), {
  'DESCRIPTOR' : _REVIEWDATA,
  '__module__' : 'reviews_pb2'
  # @@protoc_insertion_point(class_scope:ReviewData)
  })
_sym_db.RegisterMessage(ReviewData)

ReviewDataResponse = _reflection.GeneratedProtocolMessageType('ReviewDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _REVIEWDATARESPONSE,
  '__module__' : 'reviews_pb2'
  # @@protoc_insertion_point(class_scope:ReviewDataResponse)
  })
_sym_db.RegisterMessage(ReviewDataResponse)

_REVIEWS = DESCRIPTOR.services_by_name['Reviews']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REVIEWBYIDREQUEST._serialized_start=17
  _REVIEWBYIDREQUEST._serialized_end=55
  _REVIEWSBYGAMEREQUEST._serialized_start=57
  _REVIEWSBYGAMEREQUEST._serialized_end=116
  _REVIEWDATA._serialized_start=119
  _REVIEWDATA._serialized_end=323
  _REVIEWDATARESPONSE._serialized_start=325
  _REVIEWDATARESPONSE._serialized_end=375
  _REVIEWS._serialized_start=377
  _REVIEWS._serialized_end=494
# @@protoc_insertion_point(module_scope)
