version: "3.8"
services:            
    gateway:
        environment:
            STEAM_HOST: steam
            USERS_HOST: users
            REVIEWS_HOST: reviews
            GAMES_HOST: games
        image: gateway
        container_name: gateway
        networks:
            - microservices
        ports:
            - 5000:5000

    steam:
        environment:
            USERS_HOST: users
            GAMES_HOST: games
        image: steam
        container_name: steam
        networks:
            - microservices
        ports:
            - 50050:50050

    games:
        environment:
            REVIEWS_HOST: reviews
        image: games
        container_name: games
        networks:
            - microservices
        ports:
            - 50051:50051
            
    users:
        image: users
        container_name: users
        networks:
            - microservices
        ports:
            - 50052:50052

    reviews:
        image: reviews
        container_name: reviews
        networks:
            - microservices
        ports:
            - 50053:50053

networks:
    microservices:
