# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: steam.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bsteam.proto\".\n\x17RecommendedGamesRequest\x12\x13\n\x0bmax_results\x18\x01 \x01(\x05\"U\n\x08GameInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x16\n\x0ereviews_number\x18\x03 \x01(\x05\x12\x17\n\x0frecommend_count\x18\x04 \x01(\x05\"-\n\x11GamesInfoResponse\x12\x18\n\x05games\x18\x01 \x03(\x0b\x32\t.GameInfo2I\n\x05Steam\x12@\n\x10RecommendedGames\x12\x18.RecommendedGamesRequest\x1a\x12.GamesInfoResponseb\x06proto3')



_RECOMMENDEDGAMESREQUEST = DESCRIPTOR.message_types_by_name['RecommendedGamesRequest']
_GAMEINFO = DESCRIPTOR.message_types_by_name['GameInfo']
_GAMESINFORESPONSE = DESCRIPTOR.message_types_by_name['GamesInfoResponse']
RecommendedGamesRequest = _reflection.GeneratedProtocolMessageType('RecommendedGamesRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECOMMENDEDGAMESREQUEST,
  '__module__' : 'steam_pb2'
  # @@protoc_insertion_point(class_scope:RecommendedGamesRequest)
  })
_sym_db.RegisterMessage(RecommendedGamesRequest)

GameInfo = _reflection.GeneratedProtocolMessageType('GameInfo', (_message.Message,), {
  'DESCRIPTOR' : _GAMEINFO,
  '__module__' : 'steam_pb2'
  # @@protoc_insertion_point(class_scope:GameInfo)
  })
_sym_db.RegisterMessage(GameInfo)

GamesInfoResponse = _reflection.GeneratedProtocolMessageType('GamesInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _GAMESINFORESPONSE,
  '__module__' : 'steam_pb2'
  # @@protoc_insertion_point(class_scope:GamesInfoResponse)
  })
_sym_db.RegisterMessage(GamesInfoResponse)

_STEAM = DESCRIPTOR.services_by_name['Steam']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RECOMMENDEDGAMESREQUEST._serialized_start=15
  _RECOMMENDEDGAMESREQUEST._serialized_end=61
  _GAMEINFO._serialized_start=63
  _GAMEINFO._serialized_end=148
  _GAMESINFORESPONSE._serialized_start=150
  _GAMESINFORESPONSE._serialized_end=195
  _STEAM._serialized_start=197
  _STEAM._serialized_end=270
# @@protoc_insertion_point(module_scope)
