# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: games.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgames.proto\"V\n\tGamesData\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x16\n\x0ereviews_number\x18\x03 \x01(\x05\x12\x17\n\x0frecommend_count\x18\x04 \x01(\x05\"2\n\x1bGetMostReviewedGamesRequest\x12\x13\n\x0bmax_results\x18\x01 \x01(\x05\"5\n\x1eGetMostRecommendedGamesRequest\x12\x13\n\x0bmax_results\x18\x01 \x01(\x05\"-\n\x11GamesDataResponse\x12\x18\n\x04game\x18\x01 \x03(\x0b\x32\n.GamesData\"\x1d\n\x0fGameByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"!\n\x11GameByNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t2\xe9\x01\n\x05Games\x12<\n\x08GetGames\x12\x1c.GetMostReviewedGamesRequest\x1a\x12.GamesDataResponse\x12J\n\x13GetRecommendedGames\x12\x1f.GetMostRecommendedGamesRequest\x1a\x12.GamesDataResponse\x12(\n\x08GameByID\x12\x10.GameByIdRequest\x1a\n.GamesData\x12,\n\nGameByName\x12\x12.GameByNameRequest\x1a\n.GamesDatab\x06proto3')



_GAMESDATA = DESCRIPTOR.message_types_by_name['GamesData']
_GETMOSTREVIEWEDGAMESREQUEST = DESCRIPTOR.message_types_by_name['GetMostReviewedGamesRequest']
_GETMOSTRECOMMENDEDGAMESREQUEST = DESCRIPTOR.message_types_by_name['GetMostRecommendedGamesRequest']
_GAMESDATARESPONSE = DESCRIPTOR.message_types_by_name['GamesDataResponse']
_GAMEBYIDREQUEST = DESCRIPTOR.message_types_by_name['GameByIdRequest']
_GAMEBYNAMEREQUEST = DESCRIPTOR.message_types_by_name['GameByNameRequest']
GamesData = _reflection.GeneratedProtocolMessageType('GamesData', (_message.Message,), {
  'DESCRIPTOR' : _GAMESDATA,
  '__module__' : 'games_pb2'
  # @@protoc_insertion_point(class_scope:GamesData)
  })
_sym_db.RegisterMessage(GamesData)

GetMostReviewedGamesRequest = _reflection.GeneratedProtocolMessageType('GetMostReviewedGamesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETMOSTREVIEWEDGAMESREQUEST,
  '__module__' : 'games_pb2'
  # @@protoc_insertion_point(class_scope:GetMostReviewedGamesRequest)
  })
_sym_db.RegisterMessage(GetMostReviewedGamesRequest)

GetMostRecommendedGamesRequest = _reflection.GeneratedProtocolMessageType('GetMostRecommendedGamesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETMOSTRECOMMENDEDGAMESREQUEST,
  '__module__' : 'games_pb2'
  # @@protoc_insertion_point(class_scope:GetMostRecommendedGamesRequest)
  })
_sym_db.RegisterMessage(GetMostRecommendedGamesRequest)

GamesDataResponse = _reflection.GeneratedProtocolMessageType('GamesDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _GAMESDATARESPONSE,
  '__module__' : 'games_pb2'
  # @@protoc_insertion_point(class_scope:GamesDataResponse)
  })
_sym_db.RegisterMessage(GamesDataResponse)

GameByIdRequest = _reflection.GeneratedProtocolMessageType('GameByIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _GAMEBYIDREQUEST,
  '__module__' : 'games_pb2'
  # @@protoc_insertion_point(class_scope:GameByIdRequest)
  })
_sym_db.RegisterMessage(GameByIdRequest)

GameByNameRequest = _reflection.GeneratedProtocolMessageType('GameByNameRequest', (_message.Message,), {
  'DESCRIPTOR' : _GAMEBYNAMEREQUEST,
  '__module__' : 'games_pb2'
  # @@protoc_insertion_point(class_scope:GameByNameRequest)
  })
_sym_db.RegisterMessage(GameByNameRequest)

_GAMES = DESCRIPTOR.services_by_name['Games']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GAMESDATA._serialized_start=15
  _GAMESDATA._serialized_end=101
  _GETMOSTREVIEWEDGAMESREQUEST._serialized_start=103
  _GETMOSTREVIEWEDGAMESREQUEST._serialized_end=153
  _GETMOSTRECOMMENDEDGAMESREQUEST._serialized_start=155
  _GETMOSTRECOMMENDEDGAMESREQUEST._serialized_end=208
  _GAMESDATARESPONSE._serialized_start=210
  _GAMESDATARESPONSE._serialized_end=255
  _GAMEBYIDREQUEST._serialized_start=257
  _GAMEBYIDREQUEST._serialized_end=286
  _GAMEBYNAMEREQUEST._serialized_start=288
  _GAMEBYNAMEREQUEST._serialized_end=321
  _GAMES._serialized_start=324
  _GAMES._serialized_end=557
# @@protoc_insertion_point(module_scope)
