# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: games.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgames.proto\"2\n\x1bGetMostReviewedGamesRequest\x12\x13\n\x0bmax_results\x18\x01 \x01(\x05\"5\n\x1eGetMostRecommendedGamesRequest\x12\x13\n\x0bmax_results\x18\x01 \x01(\x05\"\x1d\n\x0fGameByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"!\n\x11GameByNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\x11\x43reateGameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"9\n\x12GameReviewsRequest\x12\x0e\n\x06\x61pp_id\x18\x01 \x01(\t\x12\x13\n\x0bmax_results\x18\x02 \x01(\x05\"V\n\tGamesData\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x16\n\x0ereviews_number\x18\x03 \x01(\x05\x12\x17\n\x0frecommend_count\x18\x04 \x01(\x05\"-\n\x11GamesDataResponse\x12\x18\n\x04game\x18\x01 \x03(\x0b\x32\n.GamesData\"\xbc\x01\n\nReviewInfo\x12\x11\n\treview_id\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x0e\n\x06review\x18\x03 \x01(\t\x12\x19\n\x11timestamp_created\x18\x04 \x01(\t\x12\x19\n\x11timestamp_updated\x18\x05 \x01(\t\x12\x13\n\x0brecommended\x18\x06 \x01(\t\x12\x15\n\rvotes_helpful\x18\x07 \x01(\x05\x12\x17\n\x0f\x61uthor_steam_id\x18\x08 \x01(\t\"2\n\x12ReviewInfoResponse\x12\x1c\n\x07reviews\x18\x01 \x03(\x0b\x32\x0b.ReviewInfo\"#\n\x10\x44\x65letionResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\x32\x8b\x03\n\x05Games\x12\x37\n\x0bGameReviews\x12\x13.GameReviewsRequest\x1a\x13.ReviewInfoResponse\x12<\n\x08GetGames\x12\x1c.GetMostReviewedGamesRequest\x1a\x12.GamesDataResponse\x12J\n\x13GetRecommendedGames\x12\x1f.GetMostRecommendedGamesRequest\x1a\x12.GamesDataResponse\x12(\n\x08GameByID\x12\x10.GameByIdRequest\x1a\n.GamesData\x12,\n\nGameByName\x12\x12.GameByNameRequest\x1a\n.GamesData\x12,\n\nCreateGame\x12\x12.CreateGameRequest\x1a\n.GamesData\x12\x39\n\x10\x44\x65leteGameByName\x12\x12.GameByNameRequest\x1a\x11.DeletionResponseb\x06proto3')



_GETMOSTREVIEWEDGAMESREQUEST = DESCRIPTOR.message_types_by_name['GetMostReviewedGamesRequest']
_GETMOSTRECOMMENDEDGAMESREQUEST = DESCRIPTOR.message_types_by_name['GetMostRecommendedGamesRequest']
_GAMEBYIDREQUEST = DESCRIPTOR.message_types_by_name['GameByIdRequest']
_GAMEBYNAMEREQUEST = DESCRIPTOR.message_types_by_name['GameByNameRequest']
_CREATEGAMEREQUEST = DESCRIPTOR.message_types_by_name['CreateGameRequest']
_GAMEREVIEWSREQUEST = DESCRIPTOR.message_types_by_name['GameReviewsRequest']
_GAMESDATA = DESCRIPTOR.message_types_by_name['GamesData']
_GAMESDATARESPONSE = DESCRIPTOR.message_types_by_name['GamesDataResponse']
_REVIEWINFO = DESCRIPTOR.message_types_by_name['ReviewInfo']
_REVIEWINFORESPONSE = DESCRIPTOR.message_types_by_name['ReviewInfoResponse']
_DELETIONRESPONSE = DESCRIPTOR.message_types_by_name['DeletionResponse']
GetMostReviewedGamesRequest = _reflection.GeneratedProtocolMessageType('GetMostReviewedGamesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETMOSTREVIEWEDGAMESREQUEST,
  '__module__' : 'games_pb2'
  # @@protoc_insertion_point(class_scope:GetMostReviewedGamesRequest)
  })
_sym_db.RegisterMessage(GetMostReviewedGamesRequest)

GetMostRecommendedGamesRequest = _reflection.GeneratedProtocolMessageType('GetMostRecommendedGamesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETMOSTRECOMMENDEDGAMESREQUEST,
  '__module__' : 'games_pb2'
  # @@protoc_insertion_point(class_scope:GetMostRecommendedGamesRequest)
  })
_sym_db.RegisterMessage(GetMostRecommendedGamesRequest)

GameByIdRequest = _reflection.GeneratedProtocolMessageType('GameByIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _GAMEBYIDREQUEST,
  '__module__' : 'games_pb2'
  # @@protoc_insertion_point(class_scope:GameByIdRequest)
  })
_sym_db.RegisterMessage(GameByIdRequest)

GameByNameRequest = _reflection.GeneratedProtocolMessageType('GameByNameRequest', (_message.Message,), {
  'DESCRIPTOR' : _GAMEBYNAMEREQUEST,
  '__module__' : 'games_pb2'
  # @@protoc_insertion_point(class_scope:GameByNameRequest)
  })
_sym_db.RegisterMessage(GameByNameRequest)

CreateGameRequest = _reflection.GeneratedProtocolMessageType('CreateGameRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEGAMEREQUEST,
  '__module__' : 'games_pb2'
  # @@protoc_insertion_point(class_scope:CreateGameRequest)
  })
_sym_db.RegisterMessage(CreateGameRequest)

GameReviewsRequest = _reflection.GeneratedProtocolMessageType('GameReviewsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GAMEREVIEWSREQUEST,
  '__module__' : 'games_pb2'
  # @@protoc_insertion_point(class_scope:GameReviewsRequest)
  })
_sym_db.RegisterMessage(GameReviewsRequest)

GamesData = _reflection.GeneratedProtocolMessageType('GamesData', (_message.Message,), {
  'DESCRIPTOR' : _GAMESDATA,
  '__module__' : 'games_pb2'
  # @@protoc_insertion_point(class_scope:GamesData)
  })
_sym_db.RegisterMessage(GamesData)

GamesDataResponse = _reflection.GeneratedProtocolMessageType('GamesDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _GAMESDATARESPONSE,
  '__module__' : 'games_pb2'
  # @@protoc_insertion_point(class_scope:GamesDataResponse)
  })
_sym_db.RegisterMessage(GamesDataResponse)

ReviewInfo = _reflection.GeneratedProtocolMessageType('ReviewInfo', (_message.Message,), {
  'DESCRIPTOR' : _REVIEWINFO,
  '__module__' : 'games_pb2'
  # @@protoc_insertion_point(class_scope:ReviewInfo)
  })
_sym_db.RegisterMessage(ReviewInfo)

ReviewInfoResponse = _reflection.GeneratedProtocolMessageType('ReviewInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _REVIEWINFORESPONSE,
  '__module__' : 'games_pb2'
  # @@protoc_insertion_point(class_scope:ReviewInfoResponse)
  })
_sym_db.RegisterMessage(ReviewInfoResponse)

DeletionResponse = _reflection.GeneratedProtocolMessageType('DeletionResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETIONRESPONSE,
  '__module__' : 'games_pb2'
  # @@protoc_insertion_point(class_scope:DeletionResponse)
  })
_sym_db.RegisterMessage(DeletionResponse)

_GAMES = DESCRIPTOR.services_by_name['Games']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETMOSTREVIEWEDGAMESREQUEST._serialized_start=15
  _GETMOSTREVIEWEDGAMESREQUEST._serialized_end=65
  _GETMOSTRECOMMENDEDGAMESREQUEST._serialized_start=67
  _GETMOSTRECOMMENDEDGAMESREQUEST._serialized_end=120
  _GAMEBYIDREQUEST._serialized_start=122
  _GAMEBYIDREQUEST._serialized_end=151
  _GAMEBYNAMEREQUEST._serialized_start=153
  _GAMEBYNAMEREQUEST._serialized_end=186
  _CREATEGAMEREQUEST._serialized_start=188
  _CREATEGAMEREQUEST._serialized_end=221
  _GAMEREVIEWSREQUEST._serialized_start=223
  _GAMEREVIEWSREQUEST._serialized_end=280
  _GAMESDATA._serialized_start=282
  _GAMESDATA._serialized_end=368
  _GAMESDATARESPONSE._serialized_start=370
  _GAMESDATARESPONSE._serialized_end=415
  _REVIEWINFO._serialized_start=418
  _REVIEWINFO._serialized_end=606
  _REVIEWINFORESPONSE._serialized_start=608
  _REVIEWINFORESPONSE._serialized_end=658
  _DELETIONRESPONSE._serialized_start=660
  _DELETIONRESPONSE._serialized_end=695
  _GAMES._serialized_start=698
  _GAMES._serialized_end=1093
# @@protoc_insertion_point(module_scope)
