# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import reviews_pb2 as reviews__pb2


class ReviewsStub(object):
    """######################
    ##### SERVICES ####### 
    ######################

    Services provided by the reviews microservice
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetReview = channel.unary_unary(
                '/Reviews/GetReview',
                request_serializer=reviews__pb2.ReviewByIdRequest.SerializeToString,
                response_deserializer=reviews__pb2.ReviewDetails.FromString,
                )
        self.GetGameReviews = channel.unary_unary(
                '/Reviews/GetGameReviews',
                request_serializer=reviews__pb2.ReviewsByGameRequest.SerializeToString,
                response_deserializer=reviews__pb2.ReviewDetailsResponse.FromString,
                )
        self.PutReview = channel.unary_unary(
                '/Reviews/PutReview',
                request_serializer=reviews__pb2.UpdateReviewByIdRequest.SerializeToString,
                response_deserializer=reviews__pb2.ReviewDetails.FromString,
                )
        self.DeleteReview = channel.unary_unary(
                '/Reviews/DeleteReview',
                request_serializer=reviews__pb2.ReviewByIdRequest.SerializeToString,
                response_deserializer=reviews__pb2.ReviewDetailsResponse.FromString,
                )
        self.PutHelpfulReview = channel.unary_unary(
                '/Reviews/PutHelpfulReview',
                request_serializer=reviews__pb2.UpdateHelpfulOnReviewByIdRequest.SerializeToString,
                response_deserializer=reviews__pb2.ReviewDetails.FromString,
                )
        self.GetGameReviewsByLanguage = channel.unary_unary(
                '/Reviews/GetGameReviewsByLanguage',
                request_serializer=reviews__pb2.GameReviewsByLanguageRequest.SerializeToString,
                response_deserializer=reviews__pb2.ReviewDetailsResponse.FromString,
                )
        self.GetReviewsByUser = channel.unary_unary(
                '/Reviews/GetReviewsByUser',
                request_serializer=reviews__pb2.ReviewsByUserIdRequest.SerializeToString,
                response_deserializer=reviews__pb2.ReviewDetailsResponse.FromString,
                )
        self.GetReviewsByHelpful = channel.unary_unary(
                '/Reviews/GetReviewsByHelpful',
                request_serializer=reviews__pb2.ReviewsByHelpfulRequest.SerializeToString,
                response_deserializer=reviews__pb2.ReviewDetailsResponse.FromString,
                )


class ReviewsServicer(object):
    """######################
    ##### SERVICES ####### 
    ######################

    Services provided by the reviews microservice
    """

    def GetReview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGameReviews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutReview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteReview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutHelpfulReview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGameReviewsByLanguage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReviewsByUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReviewsByHelpful(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReviewsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetReview': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReview,
                    request_deserializer=reviews__pb2.ReviewByIdRequest.FromString,
                    response_serializer=reviews__pb2.ReviewDetails.SerializeToString,
            ),
            'GetGameReviews': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGameReviews,
                    request_deserializer=reviews__pb2.ReviewsByGameRequest.FromString,
                    response_serializer=reviews__pb2.ReviewDetailsResponse.SerializeToString,
            ),
            'PutReview': grpc.unary_unary_rpc_method_handler(
                    servicer.PutReview,
                    request_deserializer=reviews__pb2.UpdateReviewByIdRequest.FromString,
                    response_serializer=reviews__pb2.ReviewDetails.SerializeToString,
            ),
            'DeleteReview': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteReview,
                    request_deserializer=reviews__pb2.ReviewByIdRequest.FromString,
                    response_serializer=reviews__pb2.ReviewDetailsResponse.SerializeToString,
            ),
            'PutHelpfulReview': grpc.unary_unary_rpc_method_handler(
                    servicer.PutHelpfulReview,
                    request_deserializer=reviews__pb2.UpdateHelpfulOnReviewByIdRequest.FromString,
                    response_serializer=reviews__pb2.ReviewDetails.SerializeToString,
            ),
            'GetGameReviewsByLanguage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGameReviewsByLanguage,
                    request_deserializer=reviews__pb2.GameReviewsByLanguageRequest.FromString,
                    response_serializer=reviews__pb2.ReviewDetailsResponse.SerializeToString,
            ),
            'GetReviewsByUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReviewsByUser,
                    request_deserializer=reviews__pb2.ReviewsByUserIdRequest.FromString,
                    response_serializer=reviews__pb2.ReviewDetailsResponse.SerializeToString,
            ),
            'GetReviewsByHelpful': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReviewsByHelpful,
                    request_deserializer=reviews__pb2.ReviewsByHelpfulRequest.FromString,
                    response_serializer=reviews__pb2.ReviewDetailsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Reviews', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Reviews(object):
    """######################
    ##### SERVICES ####### 
    ######################

    Services provided by the reviews microservice
    """

    @staticmethod
    def GetReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Reviews/GetReview',
            reviews__pb2.ReviewByIdRequest.SerializeToString,
            reviews__pb2.ReviewDetails.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGameReviews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Reviews/GetGameReviews',
            reviews__pb2.ReviewsByGameRequest.SerializeToString,
            reviews__pb2.ReviewDetailsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PutReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Reviews/PutReview',
            reviews__pb2.UpdateReviewByIdRequest.SerializeToString,
            reviews__pb2.ReviewDetails.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Reviews/DeleteReview',
            reviews__pb2.ReviewByIdRequest.SerializeToString,
            reviews__pb2.ReviewDetailsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PutHelpfulReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Reviews/PutHelpfulReview',
            reviews__pb2.UpdateHelpfulOnReviewByIdRequest.SerializeToString,
            reviews__pb2.ReviewDetails.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGameReviewsByLanguage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Reviews/GetGameReviewsByLanguage',
            reviews__pb2.GameReviewsByLanguageRequest.SerializeToString,
            reviews__pb2.ReviewDetailsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetReviewsByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Reviews/GetReviewsByUser',
            reviews__pb2.ReviewsByUserIdRequest.SerializeToString,
            reviews__pb2.ReviewDetailsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetReviewsByHelpful(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Reviews/GetReviewsByHelpful',
            reviews__pb2.ReviewsByHelpfulRequest.SerializeToString,
            reviews__pb2.ReviewDetailsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
